site:
  title: connectome-fs Docs
  start_page: connectome-fs::index.adoc
  url: https://amdphreak.github.io/connectome-fs/docs
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
      worktrees: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: site/public/docs
